//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CielPostal.Module.Gimba {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemEstoque", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ItemEstoque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProdutoField;
        
        private int QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemRetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodigoProduto {
            get {
                return this.CodigoProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProdutoField, value) != true)) {
                    this.CodigoProdutoField = value;
                    this.RaisePropertyChanged("CodigoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MensagemRetorno {
            get {
                return this.MensagemRetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemRetornoField, value) != true)) {
                    this.MensagemRetornoField = value;
                    this.RaisePropertyChanged("MensagemRetorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Gimba.EstoqueSoap")]
    public interface EstoqueSoap {
        
        // CODEGEN: Generating message contract since element name Itens from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atualizar", ReplyAction="*")]
        CielPostal.Module.Gimba.AtualizarResponse Atualizar(CielPostal.Module.Gimba.AtualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<CielPostal.Module.Gimba.AtualizarResponse> AtualizarAsync(CielPostal.Module.Gimba.AtualizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Atualizar", Namespace="http://tempuri.org/", Order=0)]
        public CielPostal.Module.Gimba.AtualizarRequestBody Body;
        
        public AtualizarRequest() {
        }
        
        public AtualizarRequest(CielPostal.Module.Gimba.AtualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CielPostal.Module.Gimba.ItemEstoque[] Itens;
        
        public AtualizarRequestBody() {
        }
        
        public AtualizarRequestBody(CielPostal.Module.Gimba.ItemEstoque[] Itens) {
            this.Itens = Itens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public CielPostal.Module.Gimba.AtualizarResponseBody Body;
        
        public AtualizarResponse() {
        }
        
        public AtualizarResponse(CielPostal.Module.Gimba.AtualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CielPostal.Module.Gimba.ItemEstoque[] AtualizarResult;
        
        public AtualizarResponseBody() {
        }
        
        public AtualizarResponseBody(CielPostal.Module.Gimba.ItemEstoque[] AtualizarResult) {
            this.AtualizarResult = AtualizarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstoqueSoapChannel : CielPostal.Module.Gimba.EstoqueSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstoqueSoapClient : System.ServiceModel.ClientBase<CielPostal.Module.Gimba.EstoqueSoap>, CielPostal.Module.Gimba.EstoqueSoap {
        
        public EstoqueSoapClient() {
        }
        
        public EstoqueSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstoqueSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstoqueSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstoqueSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CielPostal.Module.Gimba.AtualizarResponse CielPostal.Module.Gimba.EstoqueSoap.Atualizar(CielPostal.Module.Gimba.AtualizarRequest request) {
            return base.Channel.Atualizar(request);
        }
        
        public CielPostal.Module.Gimba.ItemEstoque[] Atualizar(CielPostal.Module.Gimba.ItemEstoque[] Itens) {
            CielPostal.Module.Gimba.AtualizarRequest inValue = new CielPostal.Module.Gimba.AtualizarRequest();
            inValue.Body = new CielPostal.Module.Gimba.AtualizarRequestBody();
            inValue.Body.Itens = Itens;
            CielPostal.Module.Gimba.AtualizarResponse retVal = ((CielPostal.Module.Gimba.EstoqueSoap)(this)).Atualizar(inValue);
            return retVal.Body.AtualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CielPostal.Module.Gimba.AtualizarResponse> CielPostal.Module.Gimba.EstoqueSoap.AtualizarAsync(CielPostal.Module.Gimba.AtualizarRequest request) {
            return base.Channel.AtualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CielPostal.Module.Gimba.AtualizarResponse> AtualizarAsync(CielPostal.Module.Gimba.ItemEstoque[] Itens) {
            CielPostal.Module.Gimba.AtualizarRequest inValue = new CielPostal.Module.Gimba.AtualizarRequest();
            inValue.Body = new CielPostal.Module.Gimba.AtualizarRequestBody();
            inValue.Body.Itens = Itens;
            return ((CielPostal.Module.Gimba.EstoqueSoap)(this)).AtualizarAsync(inValue);
        }
    }
}
