//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace CielPostal.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("NumeroContrato")]
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("ACF - Contrato")]
  [DevExpress.Persistent.Base.NavigationItemAttribute("Configuração")]
  [DevExpress.Persistent.Base.ImageNameAttribute("Action_Paste")]
  public partial class ACF_Contrato : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _numeroContrato;
    private CielPostal.Module.BusinessObjects.SRO_Configuracao _sRO_Configuracao;
    private System.String _unidadeVinculacao;
    private CielPostal.Module.BusinessObjects.ZPL_Configuracao _zPL_Configuracao;
    private System.String _codigoSAP;
    private System.String _servico;
    public ACF_Contrato(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Serviço")]
    public System.String Servico
    {
      get
      {
        return _servico;
      }
      set
      {
        SetPropertyValue("Servico", ref _servico, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Código SAP")]
    public System.String CodigoSAP
    {
      get
      {
        return _codigoSAP;
      }
      set
      {
        SetPropertyValue("CodigoSAP", ref _codigoSAP, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Número Contrato")]
    public System.String NumeroContrato
    {
      get
      {
        return _numeroContrato;
      }
      set
      {
        SetPropertyValue("NumeroContrato", ref _numeroContrato, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Unidade de Vinculação")]
    public System.String UnidadeVinculacao
    {
      get
      {
        return _unidadeVinculacao;
      }
      set
      {
        SetPropertyValue("UnidadeVinculacao", ref _unidadeVinculacao, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("ACF_Contratos-ZPL_Configuracao")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Etiqueta ZPL")]
    public CielPostal.Module.BusinessObjects.ZPL_Configuracao ZPL_Configuracao
    {
      get
      {
        return _zPL_Configuracao;
      }
      set
      {
        SetPropertyValue("ZPL_Configuracao", ref _zPL_Configuracao, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("ACF_Contratos-SRO_Configuracao")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Rastreamento Objeto")]
    public CielPostal.Module.BusinessObjects.SRO_Configuracao SRO_Configuracao
    {
      get
      {
        return _sRO_Configuracao;
      }
      set
      {
        SetPropertyValue("SRO_Configuracao", ref _sRO_Configuracao, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("NFe_Headers-ACF_Contrato")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Notas Fiscais")]
    public XPCollection<CielPostal.Module.BusinessObjects.NFe_Header> NFe_Headers
    {
      get
      {
        return GetCollection<CielPostal.Module.BusinessObjects.NFe_Header>("NFe_Headers");
      }
    }
  }
}
