//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace CielPostal.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Configuração Pedido ECOM")]
  [DevExpress.Persistent.Base.NavigationItemAttribute("Configuração")]
  public partial class ESO_Configuracao : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _arquivoEstoqueGimba;
    private System.String _uRLGimba;
    private System.String _pastaACOM;
    public ESO_Configuracao(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Pasta ACOM")]
    public System.String PastaACOM
    {
      get
      {
        return _pastaACOM;
      }
      set
      {
        SetPropertyValue("PastaACOM", ref _pastaACOM, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("URL Gimba")]
    public System.String URLGimba
    {
      get
      {
        return _uRLGimba;
      }
      set
      {
        SetPropertyValue("URLGimba", ref _uRLGimba, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Arquivo Estoque Gimba")]
    public System.String ArquivoEstoqueGimba
    {
      get
      {
        return _arquivoEstoqueGimba;
      }
      set
      {
        SetPropertyValue("ArquivoEstoqueGimba", ref _arquivoEstoqueGimba, value);
      }
    }
  }
}
