//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace CielPostal.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("NumeroPedido")]
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Pedidos ECOM")]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Invoice")]
  [DevExpress.Persistent.Base.NavigationItemAttribute("Consulta")]
  public partial class ESO_Header : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.DateTime _dataEmissao;
    private System.String _pedidoParceiro;
    private System.String _parceiro;
    public ESO_Header(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Parceiro")]
    public System.String Parceiro
    {
      get
      {
        return _parceiro;
      }
      set
      {
        SetPropertyValue("Parceiro", ref _parceiro, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Data Emissão")]
    public System.DateTime DataEmissao
    {
      get
      {
        return _dataEmissao;
      }
      set
      {
        SetPropertyValue("DataEmissao", ref _dataEmissao, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Nro. Pedido Parceiro")]
    public System.String PedidoParceiro
    {
      get
      {
        return _pedidoParceiro;
      }
      set
      {
        SetPropertyValue("PedidoParceiro", ref _pedidoParceiro, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("ESO_Items-ESO_Header")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Itens")]
    public XPCollection<CielPostal.Module.BusinessObjects.ESO_Item> ESO_Items
    {
      get
      {
        return GetCollection<CielPostal.Module.BusinessObjects.ESO_Item>("ESO_Items");
      }
    }
  }
}
