//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace CielPostal.Module.BusinessObjects
{
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("NF - Rastreamento(s)")]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("Descricao")]
  [DevExpress.Persistent.Base.DefaultClassOptionsAttribute]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Vendor")]
  [DevExpress.Persistent.Base.NavigationItemAttribute("NaoVisivel")]
  public partial class NFe_SRO : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.TimeSpan _hora;
    private System.DateTime _data;
    private System.String _sTO;
    private System.String _uF;
    private System.String _cidade;
    private System.String _codigo;
    private System.String _local;
    private System.String _comentario;
    private System.String _documento;
    private System.String _recebedor;
    private System.String _descricao;
    private CielPostal.Module.BusinessObjects.SRO_Evento _sRO_Evento;
    private CielPostal.Module.BusinessObjects.NFe_Header _nFe_Header;
    public NFe_SRO(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("NFe_SROs-NFe_Header")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Nota Fiscal")]
    public CielPostal.Module.BusinessObjects.NFe_Header NFe_Header
    {
      get
      {
        return _nFe_Header;
      }
      set
      {
        SetPropertyValue("NFe_Header", ref _nFe_Header, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("NFe_SROs-SRO_Evento")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Evento")]
    public CielPostal.Module.BusinessObjects.SRO_Evento SRO_Evento
    {
      get
      {
        return _sRO_Evento;
      }
      set
      {
        SetPropertyValue("SRO_Evento", ref _sRO_Evento, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Data")]
    [DevExpress.Xpo.SizeAttribute(10)]
    public System.DateTime Data
    {
      get
      {
        return _data;
      }
      set
      {
        SetPropertyValue("Data", ref _data, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(5)]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Hora")]
    public System.TimeSpan Hora
    {
      get
      {
        return _hora;
      }
      set
      {
        SetPropertyValue("Hora", ref _hora, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Descrição")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Descricao
    {
      get
      {
        return _descricao;
      }
      set
      {
        SetPropertyValue("Descricao", ref _descricao, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Recebedor")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Recebedor
    {
      get
      {
        return _recebedor;
      }
      set
      {
        SetPropertyValue("Recebedor", ref _recebedor, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Documento")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Documento
    {
      get
      {
        return _documento;
      }
      set
      {
        SetPropertyValue("Documento", ref _documento, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Comentário")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Comentario
    {
      get
      {
        return _comentario;
      }
      set
      {
        SetPropertyValue("Comentario", ref _comentario, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Local")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Local
    {
      get
      {
        return _local;
      }
      set
      {
        SetPropertyValue("Local", ref _local, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Código")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Codigo
    {
      get
      {
        return _codigo;
      }
      set
      {
        SetPropertyValue("Codigo", ref _codigo, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Município")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String Cidade
    {
      get
      {
        return _cidade;
      }
      set
      {
        SetPropertyValue("Cidade", ref _cidade, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("UF")]
    [DevExpress.Xpo.SizeAttribute(2)]
    public System.String UF
    {
      get
      {
        return _uF;
      }
      set
      {
        SetPropertyValue("UF", ref _uF, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("STO")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String STO
    {
      get
      {
        return _sTO;
      }
      set
      {
        SetPropertyValue("STO", ref _sTO, value);
      }
    }
  }
}
