//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace CielPostal.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Sonda - NFe")]
  [DevExpress.Persistent.Base.NavigationItemAttribute("Configuração")]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Security_Permission_Type")]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("ConnectionString")]
  public partial class Sonda_NFe : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _sQLNFe;
    private System.Int64 _intervaloConsulta;
    private System.String _connectionString;
    public Sonda_NFe(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("String de Conexão")]
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String ConnectionString
    {
      get
      {
        return _connectionString;
      }
      set
      {
        SetPropertyValue("ConnectionString", ref _connectionString, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Intervalo de Consulta (ms)")]
    public System.Int64 IntervaloConsulta
    {
      get
      {
        return _intervaloConsulta;
      }
      set
      {
        SetPropertyValue("IntervaloConsulta", ref _intervaloConsulta, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("SQL NFe")]
    [DevExpress.Xpo.SizeAttribute(-1)]
    public System.String SQLNFe
    {
      get
      {
        return _sQLNFe;
      }
      set
      {
        SetPropertyValue("SQLNFe", ref _sQLNFe, value);
      }
    }
  }
}
