//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace CielPostal.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("Descricao")]
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("ZPL - Etiqueta")]
  [DevExpress.Persistent.Base.NavigationItemAttribute("Configuração")]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Contract")]
  public partial class ZPL_Configuracao : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _enderecoTemporario;
    private System.Boolean _autenticarUsuario;
    private System.String _dominio;
    private System.String _senha;
    private System.String _usuario;
    private System.String _codigoZPL;
    private System.String _enderecoImpressora;
    private System.String _descricao;
    public ZPL_Configuracao(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("ACF_Contratos-ZPL_Configuracao")]
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("ACF - Contratos")]
    public XPCollection<CielPostal.Module.BusinessObjects.ACF_Contrato> ACF_Contratos
    {
      get
      {
        return GetCollection<CielPostal.Module.BusinessObjects.ACF_Contrato>("ACF_Contratos");
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Descrição")]
    public System.String Descricao
    {
      get
      {
        return _descricao;
      }
      set
      {
        SetPropertyValue("Descricao", ref _descricao, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Endereço Temp")]
    public System.String EnderecoTemporario
    {
      get
      {
        return _enderecoTemporario;
      }
      set
      {
        SetPropertyValue("EnderecoTemporario", ref _enderecoTemporario, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Endereço Impressora")]
    [DevExpress.Xpo.SizeAttribute(255)]
    public System.String EnderecoImpressora
    {
      get
      {
        return _enderecoImpressora;
      }
      set
      {
        SetPropertyValue("EnderecoImpressora", ref _enderecoImpressora, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Requer Autenticação")]
    public System.Boolean AutenticarUsuario
    {
      get
      {
        return _autenticarUsuario;
      }
      set
      {
        SetPropertyValue("AutenticarUsuario", ref _autenticarUsuario, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Domínio")]
    public System.String Dominio
    {
      get
      {
        return _dominio;
      }
      set
      {
        SetPropertyValue("Dominio", ref _dominio, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Usuário")]
    public System.String Usuario
    {
      get
      {
        return _usuario;
      }
      set
      {
        SetPropertyValue("Usuario", ref _usuario, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Senha")]
    public System.String Senha
    {
      get
      {
        return _senha;
      }
      set
      {
        SetPropertyValue("Senha", ref _senha, value);
      }
    }
    [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Código ZPL")]
    [DevExpress.Xpo.SizeAttribute(-1)]
    public System.String CodigoZPL
    {
      get
      {
        return _codigoZPL;
      }
      set
      {
        SetPropertyValue("CodigoZPL", ref _codigoZPL, value);
      }
    }
  }
}
