//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CielPostal.Svc.ServiceNFe_Method {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CielPostal.Wcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNFe_Method.INFe_Method")]
    public interface INFe_Method {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/GetData", ReplyAction="http://tempuri.org/INFe_Method/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/GetData", ReplyAction="http://tempuri.org/INFe_Method/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/GetDataUsingDataContract", ReplyAction="http://tempuri.org/INFe_Method/GetDataUsingDataContractResponse")]
        CielPostal.Svc.ServiceNFe_Method.CompositeType GetDataUsingDataContract(CielPostal.Svc.ServiceNFe_Method.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/GetDataUsingDataContract", ReplyAction="http://tempuri.org/INFe_Method/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CielPostal.Svc.ServiceNFe_Method.CompositeType> GetDataUsingDataContractAsync(CielPostal.Svc.ServiceNFe_Method.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/CreateNFe", ReplyAction="http://tempuri.org/INFe_Method/CreateNFeResponse")]
        void CreateNFe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/CreateNFe", ReplyAction="http://tempuri.org/INFe_Method/CreateNFeResponse")]
        System.Threading.Tasks.Task CreateNFeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/UpdateSRONFe", ReplyAction="http://tempuri.org/INFe_Method/UpdateSRONFeResponse")]
        void UpdateSRONFe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/UpdateSRONFe", ReplyAction="http://tempuri.org/INFe_Method/UpdateSRONFeResponse")]
        System.Threading.Tasks.Task UpdateSRONFeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/CapturarPedidos", ReplyAction="http://tempuri.org/INFe_Method/CapturarPedidosResponse")]
        void CapturarPedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/CapturarPedidos", ReplyAction="http://tempuri.org/INFe_Method/CapturarPedidosResponse")]
        System.Threading.Tasks.Task CapturarPedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/AtualizarEstoque", ReplyAction="http://tempuri.org/INFe_Method/AtualizarEstoqueResponse")]
        void AtualizarEstoque();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INFe_Method/AtualizarEstoque", ReplyAction="http://tempuri.org/INFe_Method/AtualizarEstoqueResponse")]
        System.Threading.Tasks.Task AtualizarEstoqueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INFe_MethodChannel : CielPostal.Svc.ServiceNFe_Method.INFe_Method, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFe_MethodClient : System.ServiceModel.ClientBase<CielPostal.Svc.ServiceNFe_Method.INFe_Method>, CielPostal.Svc.ServiceNFe_Method.INFe_Method {
        
        public NFe_MethodClient() {
        }
        
        public NFe_MethodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFe_MethodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFe_MethodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFe_MethodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CielPostal.Svc.ServiceNFe_Method.CompositeType GetDataUsingDataContract(CielPostal.Svc.ServiceNFe_Method.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CielPostal.Svc.ServiceNFe_Method.CompositeType> GetDataUsingDataContractAsync(CielPostal.Svc.ServiceNFe_Method.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void CreateNFe() {
            base.Channel.CreateNFe();
        }
        
        public System.Threading.Tasks.Task CreateNFeAsync() {
            return base.Channel.CreateNFeAsync();
        }
        
        public void UpdateSRONFe() {
            base.Channel.UpdateSRONFe();
        }
        
        public System.Threading.Tasks.Task UpdateSRONFeAsync() {
            return base.Channel.UpdateSRONFeAsync();
        }
        
        public void CapturarPedidos() {
            base.Channel.CapturarPedidos();
        }
        
        public System.Threading.Tasks.Task CapturarPedidosAsync() {
            return base.Channel.CapturarPedidosAsync();
        }
        
        public void AtualizarEstoque() {
            base.Channel.AtualizarEstoque();
        }
        
        public System.Threading.Tasks.Task AtualizarEstoqueAsync() {
            return base.Channel.AtualizarEstoqueAsync();
        }
    }
}
