-- alterar as variaveis periodo e data toda vez que for rodar o select.

declare @periodo varchar(11);
declare @data varchar(6);

set @periodo = '01/11/2017;'; -- Ex 01/mm/yyyy
set @data    =  '201711'; -- Ex yyyymm

SELECT
  B01.TSOP_CLISAPCLINOM
  ,A01.TFIS_NOTFISCLI
 ,C01.TSIS_CNPJ


 ,SUM(CASE WHEN D01.TFIS_TIPO = 'E' THEN -1 ELSE 1 END * A01.TFIS_NOTFISVAL) 
 ,SUM(CASE WHEN D01.TFIS_TIPO = 'E' THEN -1 ELSE 1 END * ABS(F01.TFIS_NOTFISQTD) * COALESCE(E01.TFIS_ITEPARDED,0.00)) AS TFIS_NOTFISVALDED
 ,@periodo+ TSIS_CNPJ +';'+REPLACE(SUM(CASE WHEN D01.TFIS_TIPO = 'E' THEN -1 ELSE 1 END * A01.TFIS_NOTFISVAL),'.',',')+';'+REPLACE(SUM(CASE WHEN D01.TFIS_TIPO = 'E' THEN -1 ELSE 1 END * ABS(F01.TFIS_NOTFISQTD) * COALESCE(E01.TFIS_ITEPARDED,0.00)),'.',',')

FROM TFIS_NOTAFISCAL A01 with (nolock) INNER JOIN TSOP_ClienteSAP       B01 ON ( A01.TFIS_NOTFISCLI    = B01.TSOP_CLISAPCLICOD )
                         INNER JOIN TFIS_Cliente          C01 ON ( B01.TSOP_CLISAPCLICGC = C01.TSIS_CNPJ         )
						 INNER JOIN TFIS_CFOP             D01 ON ( A01.TFIS_NOTFISCFO    = D01.TFIS_CFOP         )
						 LEFT  JOIN VFIS_ParcelaDedutivel E01 ON ( A01.TFIS_NOTFISANOMES = E01.TFIS_PARDEDANOMES
						                                       AND A01.TFIS_NOTFISITE    = E01.TFIS_ITECOD       )
				         INNER JOIN (
										SELECT CONVERT(CHAR(06),TSOP_ORDBILDATDOC,112) AS TFIS_NOTFISANOMES
											  ,SUBSTRING(TSOP_ORDBILNRODOC,1,9) AS TFIS_NOTFISNUM
											  ,TSOP_ORDBILITECOD AS TFIS_NOTFISITE
											  ,SUM(TSOP_ORDBILQTD) AS TFIS_NOTFISQTD
										FROM TSOP_OrderBilling
										WHERE TSOP_ORDBILTIPDOC IN ('Billing','Return')
										-- COLOQUEI ESSE NOT IN PARA O MES DE NOVEMBRO PARA TIRAR AS NOTAS CANCELADAS. PARA O PROXIMO MES COMENTA ESSA LINHA.
									--	AND NOT  TSOP_ORDBILNRODOC IN ('000211645-7','000211343-7','000211647-7','000211342-7','000211167-7')
										GROUP BY CONVERT(CHAR(06),TSOP_ORDBILDATDOC,112)
												,SUBSTRING(TSOP_ORDBILNRODOC,1,9)
												,TSOP_ORDBILITECOD
						                                ) F01 ON ( A01.TFIS_NOTFISANOMES = F01.TFIS_NOTFISANOMES
														       AND A01.TFIS_NOTFISNUM    = F01.TFIS_NOTFISNUM   
														       AND A01.TFIS_NOTFISITE    = F01.TFIS_NOTFISITE    )
														       
				
														       
WHERE A01.TFIS_NOTFISANOMES = @data
  and not (A01.TFIS_NOTFISCLI = '6786453' and A01.TFIS_NOTFISNUM = 492)
GROUP BY B01.TSOP_CLISAPCLINOM
  ,A01.TFIS_NOTFISCLI
        ,C01.TSIS_CNPJ


-- para saber notas canceladas
declare @periodo varchar(11);
declare @data varchar(6);

set @periodo = '01/11/2017;'; -- Ex 01/mm/yyyy
set @data =  '201711'; -- Ex yyyymm

 select TFIS_NOTFISVAL FROM TFIS_NOTAFISCAL A01 
       INNER JOIN (
										SELECT  CONVERT(CHAR(06),TSOP_ORDBILDATDOC,112) AS TFIS_NOTFISANOMES
											  ,SUBSTRING(TSOP_ORDBILNRODOC,1,9) AS TFIS_NOTFISNUM
											  ,TSOP_ORDBILITECOD AS TFIS_NOTFISITE
											  ,SUM(TSOP_ORDBILQTD) AS TFIS_NOTFISQTD
										FROM TSOP_OrderBilling
										WHERE TSOP_ORDBILTIPDOC IN ('Return')
										GROUP BY CONVERT(CHAR(06),TSOP_ORDBILDATDOC,112)
												,SUBSTRING(TSOP_ORDBILNRODOC,1,9)
												,TSOP_ORDBILITECOD
						                                ) F01 ON ( A01.TFIS_NOTFISANOMES = F01.TFIS_NOTFISANOMES
														       AND A01.TFIS_NOTFISNUM    = F01.TFIS_NOTFISNUM   
														       AND A01.TFIS_NOTFISITE    = F01.TFIS_NOTFISITE    )
where A01.TFIS_NOTFISCLI = '7465515'
and A01.TFIS_NOTFISANOMES = @data

select * from TFIS_CFOP

select * from TSOP_OrderBilling where SUBSTRING(TSOP_ORDBILNRODOC,1,9) = 174607
select * from TFIS_NOTAFISCAL  where TFIS_NOTFISNUM = 174607

select * from TSOP_OrderBilling where SUBSTRING(TSOP_ORDBILNRODOC,1,9) = 175858
select * from TFIS_NOTAFISCAL  where TFIS_NOTFISNUM = 175858


select * from TFIS_NOTAFISCAL with (nolock) where TFIS_NOTFISANOMES = '201711'

select * from VFIS_ParcelaDedutivel where TFIS_ITECOD = 'Y3954354'
select * from VFIS_ParcelaDedutivel where TFIS_ITECOD = 'Y3952619'


SELECT
  B01.TSOP_CLISAPCLINOM
 ,C01.TSIS_CNPJ
 ,CASE WHEN D01.TFIS_TIPO = 'E' THEN -1 ELSE 1 END * A01.TFIS_NOTFISVAL AS TFIS_NOTFISVAL
 ,CASE WHEN D01.TFIS_TIPO = 'E' THEN -1 ELSE 1 END * F01.TFIS_NOTFISQTD * COALESCE(E01.TFIS_ITEPARDED,0.00) AS TFIS_NOTFISVALDED
FROM TFIS_NOTAFISCAL A01 INNER JOIN TSOP_ClienteSAP       B01 ON ( A01.TFIS_NOTFISCLI    = B01.TSOP_CLISAPCLICOD )
                         INNER JOIN TFIS_Cliente          C01 ON ( B01.TSOP_CLISAPCLICGC = C01.TSIS_CNPJ         )
						 INNER JOIN TFIS_CFOP             D01 ON ( A01.TFIS_NOTFISCFO    = D01.TFIS_CFOP         )
						 LEFT  JOIN VFIS_ParcelaDedutivel E01 ON ( A01.TFIS_NOTFISANOMES = E01.TFIS_PARDEDANOMES
						                                       AND A01.TFIS_NOTFISITE    = E01.TFIS_ITECOD       )
				         INNER JOIN (
										SELECT CONVERT(CHAR(06),TSOP_ORDBILDATDOC,112) AS TFIS_NOTFISANOMES
											  ,SUBSTRING(TSOP_ORDBILNRODOC,1,9) AS TFIS_NOTFISNUM
											  ,TSOP_ORDBILITECOD AS TFIS_NOTFISITE
											  ,SUM(TSOP_ORDBILQTD) AS TFIS_NOTFISQTD
										FROM TSOP_OrderBilling
										WHERE TSOP_ORDBILTIPDOC IN ('Billing', 'Return')
										GROUP BY CONVERT(CHAR(06),TSOP_ORDBILDATDOC,112)
												,SUBSTRING(TSOP_ORDBILNRODOC,1,9)
												,TSOP_ORDBILITECOD
						                                ) F01 ON ( A01.TFIS_NOTFISANOMES = F01.TFIS_NOTFISANOMES
														       AND A01.TFIS_NOTFISNUM    = F01.TFIS_NOTFISNUM   
														       AND A01.TFIS_NOTFISITE    = F01.TFIS_NOTFISITE    )
WHERE A01.TFIS_NOTFISANOMES = '201604'
  AND C01.TSIS_CNPJ = '59104760000353'



  select * from TFIS_NOTAFISCAL