CREATE TABLE M_PRODUTO
(
  PRODUTO_ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(100),
  QTDE INT,
  PRECO DECIMAL(10,2)
)

SELECT * FROM M_PRODUTO

INSERT INTO M_PRODUTO(NOME,   QTDE, PRECO)  VALUES ('CAMISA',  100, 29.99)
INSERT INTO M_PRODUTO(NOME, QTDE, PRECO) VALUES ('CALÇA', 200, 39.99)
INSERT INTO M_PRODUTO(NOME, QTDE, PRECO) VALUES ('CUECA', 600, 9.99)
INSERT INTO M_PRODUTO(NOME, QTDE, PRECO) VALUES ('CAMISETA', 400, 19.99)


DELETE FROM M_PRODUTO WHERE PRODUTO_ID = 4


UPDATE M_PRODUTO
SET NOME = 'CAMISA POLO'
WHERE PRODUTO_ID = 1


DROP TABLE M_CLIENTE

CREATE TABLE M_CLIENTE
(
  CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(100),
  EMAIL VARCHAR(100),
  TELEFONE VARCHAR(15),
  CPF VARCHAR(12)
)

SELECT * FROM M_CLIENTE

INSERT INTO M_CLIENTE (NOME, EMAIL, TELEFONE, CPF) VALUES ( 'MARCOS', 'MARCOS@GMAIL.COM', '5544-4455','23.444.333')

DROP TABLE M_VENDAS

CREATE TABLE M_VENDAS
(
  CODVENDA INT IDENTITY(1,1) PRIMARY KEY,
  CODCLIENTE INT,
  DATA DATETIME DEFAULT GETDATE()
)

INSERT INTO M_VENDAS( CODCLIENTE ) VALUES ( 1)

SELECT * FROM M_VENDAS

CREATE TABLE M_ITENS
(
  CODITEM INT IDENTITY(1,1),
  CODVENDA INT,
  CODIGOPRODUTO INT,
  QTDE INT,
  PRECO DECIMAL(12,2)
)

INSERT INTO M_ITENS (CODVENDA, CODIGOPRODUTO, QTDE, PRECO) VALUES (1, 1, 5, 29.99)

INSERT INTO M_ITENS (CODVENDA, CODIGOPRODUTO, QTDE, PRECO) VALUES (1, 2, 15, 39.99)
INSERT INTO M_ITENS (CODVENDA, CODIGOPRODUTO, QTDE, PRECO) VALUES (1, 3, 25, 9.99)
INSERT INTO M_ITENS (CODVENDA, CODIGOPRODUTO, QTDE, PRECO) VALUES (1, 5, 45, 19.99)

SELECT *  FROM M_ITENS WHERE PRECO = (SELECT MAX(PRECO) FROM M_ITENS)



CODVENDA, DATA, NOMECLIENTE, CODIGOPRODUTO, NOME DO PRODUTO, QTDE, PRECO


SELECT I.CODVENDA, V.DATA, C.NOME, P.PRODUTO_ID, P.NOME, I.QTDE, I.PRECO, (I.QTDE * I.PRECO) AS SUBTOTAL
FROM M_ITENS I 
INNER JOIN M_VENDAS V ON V.CODVENDA = I.CODVENDA
INNER JOIN M_CLIENTE C ON C.CLIENTE_ID = V.CODCLIENTE
INNER JOIN M_PRODUTO P ON P.PRODUTO_ID = I.CODIGOPRODUTO




CRIAR TABELA
APAGAR TABELA

SELECIONAR REGISTRO
INSERIR REGISTRO
APAGAR REGISTRO
ALTERAR REGISTRO

UNIR 2 OU MAIS TABELAS



